import type { Metadata } from "next";
import { jersey10 } from "./ui/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey10.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
