'use client'
export default function CareerJourney() {
    return (
    <section >
        <h1>this is the career page</h1>
        <p className="text-[50px]">
        hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
            hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
            hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
        </p>
    </section>)
}