export default function Certificates() {
    return (
        <section >
        <h1>this is the Certificates page</h1>
        <p className="text-[50px]">
        hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
            hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
            hihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflkhihihi
            sdfkgmsdf
            dsfgsdfgsdfgnsdflk
        </p>
    </section>
    )
}